[package]
name = "bench-identity"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
protobuf = "3.7.2"
rand = "0.10.0"
x25519-dalek = "2.0.1"

[build-dependencies]
protobuf-codegen = "3.7.2"
protoc-bin-vendored = "3.2.0"
protoc-rust = "2.28.0"
